---
title: "M/STAT 501 Fall 2025 Course Calendar"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_depth: 2
    toc_float: true
    css: styles.css
  pdf_document:
    toc: false
    toc_depth: '2'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### [Back to M/STAT 501 syllabus...](index.html)

STAT 501 aims to cover Chapters 1--4 in Casella and Berger, continuing with Chapters 5--10 in STAT 502 next semester. 

# Week 1: Aug 20--22

#### _Wednesday_

* Introductions to the course and each other  
* Sections 1.1--1.2.1: Set theory, sigma algebra, basics of probability theory

#### _Friday_ 

* Section 1.2.2: Calculus of probabilities

---

# Week 2: Aug 25--29

#### _Monday_

* Section 1.2.2: Calculus of probabilities (cont)

#### _Wednesday_

* Section 1.2.3--1.2.4: Combinatorics in probability
* **Homework 1 due** (Sections 1.1--1.2.2) in [Gradescope](https://www.gradescope.com) by 5:00pm

#### _Friday_

* Section 1.2.3--1.2.4: Combinatorics in probability (cont)

---

# Week 3: Sep 1--5

#### _Monday_

* _No classes: Labor Day_

#### _Wednesday_

* Section 1.3: Conditional probability and independence
* **_QUIZ 1_**: Section 1.1--1.2.2

#### _Friday_

* Section 1.3: Conditional probability and independence (cont)

---

# Week 4: Sep 8--12

#### _Monday_

* Section 1.3: Conditional probability and independence (cont)

#### _Wednesday_

* Section 1.4: Random variables
* Section 1.5: Distribution functions
* **Homework 2 due** (Sections 1.2.3--1.3) in [Gradescope](https://www.gradescope.com) by 5:00pm

#### _Friday_

* Section 1.5: Distribution functions (cont)

---

# Week 5: Sep 15--19

#### _Monday_

* Section 1.6: Density and mass functions

#### _Wednesday_

* Section 1.6: Density and mass functions (cont)
* **_QUIZ 2_**: Sections 1.2.3--1.3

#### _Friday_

* Section 2.1: Distributions of functions of a random variable 

---

# Week 6: Sep 22--26

#### _Monday_

* Section 2.1: Distributions of functions of a random variable (cont)

#### _Wednesday_

* Section 2.2: Expected values
* **Homework 3 due** (Sections 1.4--1.6) in [Gradescope](https://www.gradescope.com) by 5:00pm

#### _Friday_

* Section 2.2: Expected values (cont)

---

# Week 7: Sep 29--Oct 3

#### _Monday_

* Section 2.3: Moments and moment generating functions

#### _Wednesday_

* Section 2.3: Moments and moment generating functions (cont)
* Section 2.6: Cumulant generating functions and characteristic functions
* (Skip Section 2.4)
* **_QUIZ 3_**: Sections 1.4--1.6

#### _Friday_

* Attend the Montana ASA Chapter Meeting in Wilson Hall 001 instead of class. Register and view the schedule here: <https://samidhasshetty.github.io/MT-ASA-2025/>


---

# Week 8: Oct 6--10

#### _Monday_

* Sections 3.1 and 3.2: Discrete families of distributions

#### _Wednesday_

* Section 3.2 (cont): Discrete families of distributions
* **Homework 4 due** (Sections 2.1--2.3) in [Gradescope](https://www.gradescope.com) by 5:00pm

#### _Friday_

* Section 3.3: Continuous families of distributions



---

# Week 9: Oct 13--17

#### _Monday_

* Section 3.3 (cont): Continuous families of distributions


#### _Wednesday_

* Section 3.4: Exponential families
* Section 3.5: Location and scale families
* Section 3.6: Inequalities and Identities

#### _Friday_

* Section 4.1: Joint and marginal distributions
* **_QUIZ 4_**: Sections 2.1--2.3

---

# Week 10: Oct 20--24

#### _Monday_

* Section 4.1 (cont): Joint and marginal distributions

#### _Wednesday_

* Section 4.1 (cont): Joint and marginal distributions
* **Homework 5 due** (Sections 3.1--3.6) in [Gradescope](https://www.gradescope.com) by 5:00pm

#### _Friday_

* Section 4.1 (cont): Joint and marginal distributions


---

# Week 11: Oct 27--31

#### _Monday_

* Section 4.2: Conditional distributions and independence


#### _Wednesday_

* Section 4.4: Hierarchical models and mixture distributions
* **_QUIZ 5_**: Sections 3.1--3.6

#### _Friday_

* Section 4.4: Hierarchical models and mixture distributions (cont)

---

# Week 12: Nov 3--7

#### _Monday_ 

* Section 4.5: Covariance and correlation (bivariate)


#### _Wednesday_

* Section 4.5: Covariance and correlation (cont)
* **Homework 6 due** (Sections 4.1--4.2, 4.4) in [Gradescope](https://www.gradescope.com) by 5:00pm

#### _Friday_

* Section 4.3: Bivariate transformations

---

# Week 13: Nov 10--14

#### _Monday_

* Section 4.3: Bivariate transformations (cont)

#### _Wednesday_

* Section 4.6: Multivariate distributions
* **_QUIZ 6_**: Sections 4.1--4.2, 4.4

#### _Friday_

* Section 4.6: Multivariate distributions (cont)


---

# Week 14: Nov 17--21

#### _Monday_

* Section 4.7: Cauchy-Schwarz and Jensen's inequalities
* Covariance and correlation for random vectors (not in textbook)

#### _Wednesday_

* More on random vectors
* **Homework 7 due** (Sections 4.3, 4.5--4.7) in [Gradescope](https://www.gradescope.com) by 5:00pm

#### _Friday_

* Special topics / preview of STAT 502


---

### _Nov 24--28: Fall break_

---

# Week 15: Dec 1--5

#### _Monday_

* Special topics / preview of STAT 502


#### _Wednesday_

* **Optional group review quiz** - option to work in teams during class; this score will replace your second lowest quiz score.

<!-- **Homework 8 due** (Section 4.7, Random vectors, Review) in [Gradescope](https://www.gradescope.com) by 5:00pm -->


#### _Friday_

* Final exam review



---

# Finals week

* Final exam in Wilson Hall 1-124 on Monday, December 8, 10:00am-11:50am
